// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WyszukiwarkaLotówDR.Data;

namespace WyszukiwarkaLotówDR.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WyszukiwarkaLotówDR.Models.LotModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Obraz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Przewoznik")
                        .HasColumnType("int");

                    b.Property<double>("cenaBiletu")
                        .HasColumnType("float");

                    b.Property<DateTime>("czasPrzylotu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("czasWylotu")
                        .HasColumnType("datetime2");

                    b.Property<int>("iloscMiejsc")
                        .HasColumnType("int");

                    b.Property<string>("kodLotniskaPrzylotu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kodLotniskaWylotu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("miejscePrzylotu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("miejsceWylotu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LotyModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Obraz = "LOT.png",
                            Przewoznik = 2,
                            cenaBiletu = 459.0,
                            czasPrzylotu = new DateTime(2021, 6, 30, 10, 53, 4, 477, DateTimeKind.Local).AddTicks(8544),
                            czasWylotu = new DateTime(2021, 6, 29, 10, 53, 4, 467, DateTimeKind.Local).AddTicks(8591),
                            iloscMiejsc = 150,
                            kodLotniskaPrzylotu = "IST",
                            kodLotniskaWylotu = "WRO",
                            miejscePrzylotu = "Istambuł",
                            miejsceWylotu = "Wrocław"
                        },
                        new
                        {
                            Id = 2,
                            Obraz = "EnterAir.png",
                            Przewoznik = 1,
                            cenaBiletu = 451.0,
                            czasPrzylotu = new DateTime(2021, 6, 28, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2330),
                            czasWylotu = new DateTime(2021, 6, 28, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2243),
                            iloscMiejsc = 150,
                            kodLotniskaPrzylotu = "IST",
                            kodLotniskaWylotu = "WRO",
                            miejscePrzylotu = "Istambuł",
                            miejsceWylotu = "Kalisz"
                        },
                        new
                        {
                            Id = 3,
                            Obraz = "Ryanair.png",
                            Przewoznik = 0,
                            cenaBiletu = 452.0,
                            czasPrzylotu = new DateTime(2021, 6, 27, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2373),
                            czasWylotu = new DateTime(2021, 6, 27, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2366),
                            iloscMiejsc = 150,
                            kodLotniskaPrzylotu = "IST",
                            kodLotniskaWylotu = "WRO",
                            miejscePrzylotu = "Barcelona",
                            miejsceWylotu = "Szczecin"
                        },
                        new
                        {
                            Id = 4,
                            Obraz = "Ryanair.png",
                            Przewoznik = 0,
                            cenaBiletu = 453.0,
                            czasPrzylotu = new DateTime(2021, 6, 30, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2391),
                            czasWylotu = new DateTime(2021, 6, 30, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2384),
                            iloscMiejsc = 150,
                            kodLotniskaPrzylotu = "IST",
                            kodLotniskaWylotu = "WRO",
                            miejscePrzylotu = "Barcelona",
                            miejsceWylotu = "Wrocław"
                        },
                        new
                        {
                            Id = 5,
                            Obraz = "Ryanair.png",
                            Przewoznik = 0,
                            cenaBiletu = 453.0,
                            czasPrzylotu = new DateTime(2021, 6, 30, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2404),
                            czasWylotu = new DateTime(2021, 6, 30, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2400),
                            iloscMiejsc = 150,
                            kodLotniskaPrzylotu = "IST",
                            kodLotniskaWylotu = "WRO",
                            miejscePrzylotu = "Barcelona",
                            miejsceWylotu = "Kalisz"
                        },
                        new
                        {
                            Id = 6,
                            Obraz = "LOT.png",
                            Przewoznik = 2,
                            cenaBiletu = 453.0,
                            czasPrzylotu = new DateTime(2021, 7, 2, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2418),
                            czasWylotu = new DateTime(2021, 7, 2, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2412),
                            iloscMiejsc = 150,
                            kodLotniskaPrzylotu = "IST",
                            kodLotniskaWylotu = "WRO",
                            miejscePrzylotu = "Barcelona",
                            miejsceWylotu = "Szczecin"
                        },
                        new
                        {
                            Id = 7,
                            Obraz = "TurkishAirlines.png",
                            Przewoznik = 4,
                            cenaBiletu = 560.0,
                            czasPrzylotu = new DateTime(2021, 6, 29, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2433),
                            czasWylotu = new DateTime(2021, 6, 29, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2427),
                            iloscMiejsc = 210,
                            kodLotniskaPrzylotu = "ALN",
                            kodLotniskaWylotu = "WAR",
                            miejscePrzylotu = "Alanya",
                            miejsceWylotu = "Warszawa"
                        },
                        new
                        {
                            Id = 8,
                            Obraz = "TurkishAirlines.png",
                            Przewoznik = 4,
                            cenaBiletu = 460.0,
                            czasPrzylotu = new DateTime(2021, 6, 29, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2447),
                            czasWylotu = new DateTime(2021, 6, 29, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2442),
                            iloscMiejsc = 200,
                            kodLotniskaPrzylotu = "IST",
                            kodLotniskaWylotu = "BER",
                            miejscePrzylotu = "Istambuł",
                            miejsceWylotu = "Berlin"
                        },
                        new
                        {
                            Id = 9,
                            Obraz = "LOT.png",
                            Przewoznik = 2,
                            cenaBiletu = 160.0,
                            czasPrzylotu = new DateTime(2021, 6, 29, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2462),
                            czasWylotu = new DateTime(2021, 6, 29, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2456),
                            iloscMiejsc = 10,
                            kodLotniskaPrzylotu = "GDA",
                            kodLotniskaWylotu = "WAR",
                            miejscePrzylotu = "Gdańsk",
                            miejsceWylotu = "Warszawa"
                        },
                        new
                        {
                            Id = 10,
                            Obraz = "Ryanair.png",
                            Przewoznik = 0,
                            cenaBiletu = 760.0,
                            czasPrzylotu = new DateTime(2021, 6, 30, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2477),
                            czasWylotu = new DateTime(2021, 6, 30, 10, 53, 4, 480, DateTimeKind.Local).AddTicks(2471),
                            iloscMiejsc = 110,
                            kodLotniskaPrzylotu = "MSK",
                            kodLotniskaWylotu = "WAR",
                            miejscePrzylotu = "Moskwa",
                            miejsceWylotu = "Warszawa"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
